// frontend/src/app/dashboard/page.tsx
"use client";

import { useState, useEffect } from 'react';
import axios from 'axios';
import { 
  Users, Calendar, Clock, Briefcase, 
  Search, Bell, MoreHorizontal, TrendingUp, 
  UserCheck, UserMinus, Plus, Building2,
  CalendarClock, Star, AlertCircle, DollarSign,
  TrendingDown, CheckCircle2, Loader2, ArrowUpRight,
  ArrowDownRight, Cake
} from 'lucide-react';
import Link from 'next/link';
import React from 'react';

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3000/api/v1';

export default function MainDashboard() {
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [period, setPeriod] = useState('month');

  useEffect(() => {
    fetchDashboard();
  }, [period]);

  const fetchDashboard = async () => {
    setLoading(true);
    try {
      const token = localStorage.getItem('access_token');
      const res = await axios.get(`${API_URL}/dashboard`, {
        headers: { Authorization: `Bearer ${token}` },
        params: { period }
      });
      setData(res.data.data);
    } catch (error) {
      console.error("Error fetching dashboard:", error);
    } finally {
      setLoading(false);
    }
  };

  if (loading && !data) {
    return <DashboardSkeleton />;
  }

  const kpis = data?.kpis || {};

  return (
    <div className="space-y-8 animate-in fade-in duration-700">
      {/* Header Welcome Section */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-black text-slate-900 tracking-tight">Panel de Control</h1>
          <p className="text-slate-500 font-medium mt-1">Monitoreo en tiempo real de ABA Talent HR.</p>
        </div>
        <div className="flex items-center gap-3">
          <div className="relative group">
            <Search className="w-5 h-5 absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 group-focus-within:text-primary transition-colors" />
            <input 
              type="text" 
              placeholder="Buscar..." 
              className="input-modern pl-11 w-64 bg-white border-transparent shadow-sm focus:shadow-md transition-all"
            />
          </div>
          <Link href="/dashboard/employees/new" className="btn-primary px-6 py-3 flex items-center gap-2 shadow-lg hover:shadow-primary/20 transition-all">
            <Plus className="w-4 h-4" />
            Nuevo Registro
          </Link>
        </div>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <SummaryCard 
          kpi={kpis.totalEmployees}
          color="bg-indigo-500" 
          icon={<Users />}
        />
        <SummaryCard 
          kpi={kpis.activeEmployees}
          color="bg-emerald-500" 
          icon={<UserCheck />}
        />
        <SummaryCard 
          kpi={kpis.pendingLeaves}
          color="bg-amber-500" 
          icon={<CalendarClock />}
        />
        <SummaryCard 
          kpi={kpis.turnoverRate}
          color="bg-rose-500" 
          icon={<TrendingDown />}
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Main Attendance Chart Area */}
        <div className="lg:col-span-2 space-y-8">
          <div className="card-premium p-8 bg-white border-none shadow-sm relative overflow-hidden">
            <div className="flex items-center justify-between mb-8">
              <div>
                <h3 className="text-lg font-black text-slate-800">Tendencia Mensual</h3>
                <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mt-1">Altas vs Bajas de Personal</p>
              </div>
              <div className="flex gap-2">
                <button 
                  onClick={() => setPeriod('month')}
                  className={`px-4 py-1.5 rounded-xl text-[10px] font-black uppercase transition-all ${period === 'month' ? 'bg-primary text-white shadow-md' : 'bg-slate-50 text-slate-400 hover:bg-slate-100'}`}
                >
                  Mes
                </button>
                <button 
                  onClick={() => setPeriod('quarter')}
                  className={`px-4 py-1.5 rounded-xl text-[10px] font-black uppercase transition-all ${period === 'quarter' ? 'bg-primary text-white shadow-md' : 'bg-slate-50 text-slate-400 hover:bg-slate-100'}`}
                >
                  Trimestre
                </button>
              </div>
            </div>
            
            <div className="h-72 flex items-end justify-between gap-4 px-2 relative">
              {/* Background Lines */}
              <div className="absolute inset-0 flex flex-col justify-between pointer-events-none opacity-[0.03]">
                {[...Array(5)].map((_, i) => <div key={i} className="w-full border-t border-slate-900" />)}
              </div>

              {data?.monthlyTrends?.length > 0 ? data.monthlyTrends.map((trend: any, i: number) => {
                const max = Math.max(...data.monthlyTrends.map((t: any) => t.hires + t.terminations + 1));
                const hireHeight = (trend.hires / max) * 100;
                const termHeight = (trend.terminations / max) * 100;

                return (
                  <div key={i} className="flex-1 flex flex-col items-center gap-3 group relative z-10">
                    <div className="w-full flex items-end justify-center gap-1.5 h-64">
                      {/* Hire Bar */}
                      <div 
                        className="w-3 md:w-5 bg-emerald-500 rounded-t-lg transition-all duration-1000 relative group/bar" 
                        style={{ height: `${Math.max(5, hireHeight)}%` }}
                      >
                        <div className="absolute -top-10 left-1/2 -translate-x-1/2 bg-slate-800 text-white text-[9px] px-2 py-1 rounded opacity-0 group-hover/bar:opacity-100 transition-opacity whitespace-nowrap z-50">
                          Altas: {trend.hires}
                        </div>
                      </div>
                      {/* Termination Bar */}
                      <div 
                        className="w-3 md:w-5 bg-rose-400/30 rounded-t-lg transition-all duration-1000 relative group/bar" 
                        style={{ height: `${Math.max(3, termHeight)}%` }}
                      >
                        <div className="absolute -top-10 left-1/2 -translate-x-1/2 bg-slate-800 text-white text-[9px] px-2 py-1 rounded opacity-0 group-hover/bar:opacity-100 transition-opacity whitespace-nowrap z-50">
                          Bajas: {trend.terminations}
                        </div>
                      </div>
                    </div>
                    <span className="text-[9px] font-black text-slate-400 uppercase tracking-tighter">
                      {new Date(trend.month + '-01').toLocaleDateString('es-ES', { month: 'short' })}
                    </span>
                  </div>
                );
              }) : (
                <div className="w-full h-full flex items-center justify-center text-slate-300 font-bold italic">Cargando tendencias...</div>
              )}
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <KPIWidget kpi={kpis.absenteeismRate} color="text-amber-500" sub="Tasa de inasistencias injustificadas" />
            <KPIWidget kpi={kpis.avgPerformance} color="text-indigo-500" sub="Promedio de evaluaciones de desempeño" />
          </div>
        </div>

        {/* Right Sidebar Widgets */}
        <div className="space-y-8">
          
          {/* Recent Activity */}
          <div className="card-premium p-8 bg-white border-none shadow-sm h-fit">
            <div className="flex items-center justify-between mb-8">
              <h3 className="text-lg font-black text-slate-800">Actividad Reciente</h3>
              <div className="w-2 h-2 bg-emerald-500 rounded-full animate-pulse"></div>
            </div>
            <div className="space-y-6">
              {data?.recentActivity?.length > 0 ? data.recentActivity.map((activity: any, i: number) => (
                <div key={i} className="flex gap-4 group cursor-default">
                  <div className={`w-1 h-10 rounded-full shrink-0 ${
                    activity.severity === 'success' ? 'bg-emerald-500' :
                    activity.severity === 'error' ? 'bg-rose-500' : 'bg-primary'
                  }`}></div>
                  <div className="flex-1">
                    <div className="flex justify-between items-start">
                      <p className="text-xs font-black text-slate-800 group-hover:text-primary transition-colors">{activity.title}</p>
                      <span className="text-[9px] font-bold text-slate-400 uppercase">{formatTimestamp(activity.timestamp)}</span>
                    </div>
                    <p className="text-[11px] text-slate-500 font-medium mt-1 leading-relaxed">{activity.description}</p>
                  </div>
                </div>
              )) : (
                <p className="text-center py-10 text-slate-300 font-bold italic">No hay actividad reciente</p>
              )}
            </div>
            <button className="w-full mt-10 py-3 bg-slate-50 rounded-2xl text-[10px] font-black uppercase tracking-widest text-slate-400 hover:bg-slate-100 transition-all">
              Ver Historial Completo
            </button>
          </div>

          {/* Upcoming Birthdays */}
          <div className="card-premium p-8 bg-primary text-white border-none shadow-xl shadow-primary/20 relative overflow-hidden">
            <div className="absolute -top-4 -right-4 opacity-10">
              <Cake className="w-24 h-24" />
            </div>
            <h3 className="text-lg font-black mb-6">Próximos Cumpleaños</h3>
            <div className="space-y-5">
              {data?.upcomingBirthdays?.length > 0 ? data.upcomingBirthdays.map((bday: any, i: number) => (
                <div key={i} className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-full bg-white/20 flex items-center justify-center text-xs font-black">
                    {bday.name[0]}
                  </div>
                  <div>
                    <p className="text-xs font-bold">{bday.name}</p>
                    <p className="text-[10px] opacity-70 font-medium">{bday.departmentName} • {new Date(bday.date).toLocaleDateString([], { day: 'numeric', month: 'short' })}</p>
                  </div>
                </div>
              )) : (
                <p className="text-xs font-medium opacity-70 italic">Sin cumpleaños próximos</p>
              )}
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}

function SummaryCard({ kpi, color, icon }: { kpi: any, color: string, icon: React.ReactNode }) {
  if (!kpi) return <div className="card-premium h-40 bg-slate-50 animate-pulse"></div>;

  return (
    <div className="card-premium p-8 relative overflow-hidden group bg-white border-none shadow-sm transition-all hover:shadow-xl hover:-translate-y-1">
      <div className="flex justify-between items-start mb-6">
        <div className={`p-4 rounded-[1.5rem] text-white shadow-lg ${color} transition-transform group-hover:scale-110`}>
          {React.cloneElement(icon as React.ReactElement, { className: 'w-6 h-6' } as any)}
        </div>
        {kpi.change !== undefined && (
          <div className={`flex items-center gap-1 text-[10px] font-black uppercase tracking-widest ${kpi.trend === 'up' ? 'text-emerald-500' : kpi.trend === 'down' ? 'text-rose-500' : 'text-slate-400'}`}>
            {kpi.trend === 'up' ? <ArrowUpRight className="w-3 h-3" /> : kpi.trend === 'down' ? <ArrowDownRight className="w-3 h-3" /> : null}
            {Math.abs(kpi.change)}%
          </div>
        )}
      </div>
      <div>
        <h3 className="text-3xl font-black text-slate-900 tracking-tighter">{kpi.value}</h3>
        <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mt-1">{kpi.label}</p>
      </div>
      <div className="absolute -bottom-4 -right-4 opacity-[0.02] group-hover:opacity-[0.06] transition-opacity">
        {React.cloneElement(icon as React.ReactElement, { className: 'w-32 h-32' } as any)}
      </div>
    </div>
  );
}

function KPIWidget({ kpi, color, sub }: { kpi: any, color: string, sub: string }) {
  if (!kpi) return <div className="card-premium h-32 bg-slate-50 animate-pulse"></div>;

  return (
    <div className="card-premium p-8 flex items-center gap-8 bg-white border-none shadow-sm transition-all hover:shadow-lg">
      <div className="relative w-24 h-24 shrink-0">
        <svg className="w-full h-full transform -rotate-90" viewBox="0 0 36 36">
          <circle cx="18" cy="18" r="16" fill="none" className="text-slate-50 stroke-current" strokeWidth="3" />
          <circle cx="18" cy="18" r="16" fill="none" className={`${color.replace('text-', 'stroke-')} stroke-current transition-all duration-1000 ease-out`} strokeWidth="3" strokeDasharray={`${parseFloat(kpi.value) || 100}, 100`} strokeLinecap="round" />
        </svg>
        <div className="absolute inset-0 flex items-center justify-center">
          <span className="text-xs font-black text-slate-800 tracking-tighter">{kpi.value}</span>
        </div>
      </div>
      <div>
        <h4 className="text-base font-black text-slate-800">{kpi.label}</h4>
        <p className="text-[11px] text-slate-500 mt-2 font-medium leading-relaxed">{sub}</p>
        <div className="mt-4 flex items-center gap-2">
          <span className={`w-2 h-2 rounded-full ${kpi.trend === 'up' ? 'bg-emerald-500' : 'bg-rose-500'}`}></span>
          <span className="text-[9px] font-black uppercase tracking-widest text-slate-400">Estado: {kpi.trend === 'up' ? 'Óptimo' : 'Bajo'}</span>
        </div>
      </div>
    </div>
  );
}

function formatTimestamp(timestamp: string) {
  const date = new Date(timestamp);
  const now = new Date();
  const diff = (now.getTime() - date.getTime()) / 1000;

  if (diff < 60) return 'Ahora';
  if (diff < 3600) return `${Math.floor(diff / 60)}m`;
  if (diff < 86400) return `${Math.floor(diff / 3600)}h`;
  return `${Math.floor(diff / 86400)}d`;
}

function DashboardSkeleton() {
  return (
    <div className="space-y-8 animate-pulse">
      <div className="flex justify-between items-center">
        <div className="space-y-2">
          <div className="h-8 w-64 bg-slate-100 rounded-xl" />
          <div className="h-4 w-48 bg-slate-50 rounded-lg" />
        </div>
        <div className="h-12 w-48 bg-slate-100 rounded-2xl" />
      </div>
      <div className="grid grid-cols-4 gap-6">
        {[...Array(4)].map((_, i) => <div key={i} className="h-44 bg-white rounded-[2rem] shadow-sm border border-slate-50" />)}
      </div>
      <div className="grid grid-cols-3 gap-8">
        <div className="col-span-2 h-96 bg-white rounded-[2.5rem] shadow-sm border border-slate-50" />
        <div className="h-96 bg-white rounded-[2.5rem] shadow-sm border border-slate-50" />
      </div>
    </div>
  );
}

// frontend/src/app/features/dashboard/dashboard.component.ts
import { Component, ChangeDetectionStrategy, inject, OnInit, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink, ActivatedRoute } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { DashboardService, DashboardData, KpiCard, RecentActivity } from '../../core/services/dashboard.service';
import { CardComponent, CardHeaderComponent, CardTitleComponent, CardContentComponent } from '../../shared/components/card/card.component';
import { ButtonComponent } from '../../shared/components/button/button.component';
import { LucideAngularModule } from 'lucide-angular';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [
    CommonModule,
    RouterLink,
    FormsModule,
    CardComponent,
    CardHeaderComponent,
    CardTitleComponent,
    CardContentComponent,
    ButtonComponent,
    LucideAngularModule
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="space-y-8 animate-fadeIn">

      <!-- ═══ HEADER ═══ -->
      <div class="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h2 class="text-3xl font-bold tracking-tight bg-gradient-to-r from-primary via-emerald-400 to-teal-400 bg-clip-text text-transparent">
            Panel de Comando
          </h2>
          <p class="text-muted-foreground mt-1">Bienvenido de nuevo. Esto es lo que está pasando hoy en tu organización.</p>
        </div>
        <div class="flex items-center gap-3">
          <select
            [ngModel]="selectedPeriod()"
            (ngModelChange)="selectedPeriod.set($event); fetchDashboard()"
            class="px-3 py-2 rounded-xl border border-border bg-card/50 backdrop-blur-sm text-sm focus:ring-2 focus:ring-primary/50 focus:outline-none transition-all"
          >
            <option value="week">Última Semana</option>
            <option value="month">Último Mes</option>
            <option value="quarter">Último Trimestre</option>
            <option value="year">Último Año</option>
          </select>
          <a routerLink="/employees" class="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-gradient-to-r from-primary to-emerald-500 text-white text-sm font-semibold shadow-lg shadow-primary/25 hover:shadow-primary/40 hover:scale-[1.02] transition-all duration-200">
            <lucide-icon name="users" size="16"></lucide-icon>
            Ver Empleados
          </a>
        </div>
      </div>

      @if (!loading() && data()) {

        <!-- ═══ KPI CARDS ═══ -->
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          @for (kpi of kpiCards(); track $index) {
            <div
              class="group relative overflow-hidden rounded-2xl border border-border/50 p-5 transition-all duration-300 hover:shadow-xl hover:shadow-primary/5 hover:-translate-y-0.5 cursor-default"
              [ngClass]="kpiBg[$index]"
            >
              <div class="absolute -top-6 -right-6 w-20 h-20 rounded-full blur-2xl opacity-20 transition-opacity group-hover:opacity-40"
                [ngClass]="kpiBlobColor[$index]"
              ></div>

              <div class="relative z-10 flex items-start justify-between">
                <div>
                  <p class="text-xs font-medium text-muted-foreground uppercase tracking-wider mb-1">{{ kpi.label }}</p>
                  <p class="text-3xl font-bold tracking-tight">{{ kpi.value }}</p>
                  @if (kpi.change !== undefined) {
                    <div class="flex items-center gap-1 mt-2">
                      <span
                        class="text-xs font-semibold px-1.5 py-0.5 rounded-md"
                        [ngClass]="{
                          'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400': kpi.trend === 'up',
                          'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400': kpi.trend === 'down',
                          'bg-gray-100 text-gray-600 dark:bg-gray-900/30 dark:text-gray-400': kpi.trend === 'flat'
                        }"
                      >
                        {{ kpi.trend === 'up' ? '↑' : kpi.trend === 'down' ? '↓' : '→' }}
                        {{ kpi.change }}%
                      </span>
                    </div>
                  }
                </div>
                <div class="flex items-center justify-center w-11 h-11 rounded-xl bg-gradient-to-br from-primary/10 to-primary/5 text-primary">
                  <lucide-icon [name]="kpi.icon || 'activity'" size="22"></lucide-icon>
                </div>
              </div>
            </div>
          }
        </div>

      @if (loading()) {
        <!-- ═══ LOADING STATE ═══ -->
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          @for (_ of [1,2,3,4,5,6,7,8]; track $index) {
            <div class="rounded-2xl border border-border/50 p-5 animate-pulse">
              <div class="h-3 bg-muted rounded w-24 mb-3"></div>
              <div class="h-8 bg-muted rounded w-16 mb-2"></div>
              <div class="h-3 bg-muted rounded w-12"></div>
            </div>
          }
        </div>
      }

        <!-- ═══ CHARTS & ACTIVITY ROW ═══ -->
        <div class="grid gap-6 lg:grid-cols-7">
          <!-- Headcount by Department -->
          <div class="lg:col-span-4 rounded-2xl border border-border/50 bg-card/80 backdrop-blur-sm p-6">
            <div class="flex items-center justify-between mb-6">
              <div>
                <h3 class="text-lg font-bold">Empleados por Departamento</h3>
                <p class="text-xs text-muted-foreground mt-0.5">Distribución actual del headcount</p>
              </div>
              <lucide-icon name="bar-chart-3" size="18" class="text-muted-foreground"></lucide-icon>
            </div>
            <div class="space-y-3">
              @for (dept of data()!.headcountByDepartment; track dept.departmentName; let i = $index) {
                <div class="group">
                  <div class="flex items-center justify-between mb-1.5">
                    <span class="text-sm font-medium">{{ dept.departmentName }}</span>
                    <span class="text-sm font-bold text-primary">{{ dept.count }}</span>
                  </div>
                  <div class="h-2.5 rounded-full bg-muted overflow-hidden">
                    <div
                      class="h-full rounded-full transition-all duration-700 ease-out group-hover:brightness-110"
                      [style.width.%]="getBarWidth(dept.count)"
                      [style.background]="getBarGradient(i)"
                    ></div>
                  </div>
                </div>
              } @empty {
                <div class="text-center text-muted-foreground text-sm py-6">
                  No hay departamentos registrados
                </div>
              }
            </div>
          </div>

          <!-- Monthly Trends -->
          <div class="lg:col-span-3 rounded-2xl border border-border/50 bg-card/80 backdrop-blur-sm p-6">
            <div class="flex items-center justify-between mb-6">
              <div>
                <h3 class="text-lg font-bold">Tendencia Mensual</h3>
                <p class="text-xs text-muted-foreground mt-0.5">Ingresos vs Salidas</p>
              </div>
              <lucide-icon name="trending-up" size="18" class="text-muted-foreground"></lucide-icon>
            </div>
            <div class="space-y-3">
              @for (trend of data()!.monthlyTrends; track trend.month) {
                <div class="flex items-center gap-4 py-2 border-b border-border/30 last:border-0">
                  <span class="text-xs font-mono text-muted-foreground w-16">{{ trend.month }}</span>
                  <div class="flex-1 flex items-center gap-2">
                    <span class="flex items-center gap-1 text-xs font-semibold text-green-600 dark:text-green-400 bg-green-100/50 dark:bg-green-900/20 px-2 py-0.5 rounded-md">
                      ↑ {{ trend.hires }}
                    </span>
                    <span class="flex items-center gap-1 text-xs font-semibold text-red-600 dark:text-red-400 bg-red-100/50 dark:bg-red-900/20 px-2 py-0.5 rounded-md">
                      ↓ {{ trend.terminations }}
                    </span>
                  </div>
                  <span class="text-sm font-bold">{{ trend.headcount }}</span>
                </div>
              } @empty {
                <div class="text-center text-muted-foreground text-sm py-6">
                  Sin datos de tendencia para el período seleccionado
                </div>
              }
            </div>
          </div>
        </div>

        @if (!loading() && data()) {
          <!-- ═══ PAYROLL + LEAVES + ACTIVITY ═══ -->
          <div class="grid gap-6 lg:grid-cols-3">
        <!-- Payroll Summary -->
        <div routerLink="/payroll" class="cursor-pointer group rounded-2xl border border-border/50 bg-gradient-to-br from-card to-primary/[0.02] backdrop-blur-sm p-6 hover:shadow-xl hover:shadow-primary/5 transition-all">
          <div class="flex items-center gap-3 mb-5">
            <div class="flex items-center justify-center w-10 h-10 rounded-xl bg-gradient-to-br from-emerald-500/20 to-teal-500/20 text-emerald-600 dark:text-emerald-400 group-hover:scale-110 transition-transform">
              <lucide-icon name="dollar-sign" size="20"></lucide-icon>
            </div>
            <div>
              <h3 class="text-lg font-bold">Resumen Nómina</h3>
              <p class="text-xs text-muted-foreground">Último período procesado</p>
            </div>
          </div>
          <div class="space-y-3">
            <div class="flex justify-between items-center py-2 border-b border-border/20">
              <span class="text-sm text-muted-foreground">Bruto Total</span>
              <span class="text-sm font-bold">\${{ data()!.payrollSummary.totalGross | number:'1.2-2' }}</span>
            </div>
            <div class="flex justify-between items-center py-2 border-b border-border/20">
              <span class="text-sm text-muted-foreground">Deducciones</span>
              <span class="text-sm font-semibold text-red-500">-\${{ data()!.payrollSummary.totalDeductions | number:'1.2-2' }}</span>
            </div>
            <div class="flex justify-between items-center py-2 border-b border-border/20">
              <span class="text-sm text-muted-foreground">Bonificaciones</span>
              <span class="text-sm font-semibold text-green-600">+\${{ data()!.payrollSummary.totalBonuses | number:'1.2-2' }}</span>
            </div>
            <div class="flex justify-between items-center pt-3">
              <span class="text-sm font-semibold">Neto Total</span>
              <span class="text-lg font-bold text-primary">\${{ data()!.payrollSummary.totalNet | number:'1.2-2' }}</span>
            </div>
            <div class="text-xs text-muted-foreground text-center mt-2">{{ data()!.payrollSummary.employeeCount }} empleados • {{ data()!.payrollSummary.currency }}</div>
          </div>
        </div>

        <!-- Leave Overview -->
        <div routerLink="/leaves" class="cursor-pointer group rounded-2xl border border-border/50 bg-card/80 backdrop-blur-sm p-6 hover:shadow-xl hover:shadow-primary/5 transition-all">
          <div class="flex items-center gap-3 mb-5">
            <div class="flex items-center justify-center w-10 h-10 rounded-xl bg-gradient-to-br from-blue-500/20 to-indigo-500/20 text-blue-600 dark:text-blue-400 group-hover:scale-110 transition-transform">
              <lucide-icon name="calendar-days" size="20"></lucide-icon>
            </div>
            <div>
              <h3 class="text-lg font-bold">Gestión de Ausencias</h3>
              <p class="text-xs text-muted-foreground">Solicitudes pendientes</p>
            </div>
          </div>
            <div class="grid grid-cols-3 gap-3">
              <div class="text-center p-3 rounded-xl bg-yellow-50 dark:bg-yellow-900/10 border border-yellow-200/50 dark:border-yellow-800/30">
                <p class="text-2xl font-bold text-yellow-600 dark:text-yellow-400">{{ data()!.leaveOverview.pending }}</p>
                <p class="text-xs text-muted-foreground mt-1">Pendientes</p>
              </div>
              <div class="text-center p-3 rounded-xl bg-green-50 dark:bg-green-900/10 border border-green-200/50 dark:border-green-800/30">
                <p class="text-2xl font-bold text-green-600 dark:text-green-400">{{ data()!.leaveOverview.approved }}</p>
                <p class="text-xs text-muted-foreground mt-1">Aprobados</p>
              </div>
              <div class="text-center p-3 rounded-xl bg-red-50 dark:bg-red-900/10 border border-red-200/50 dark:border-red-800/30">
                <p class="text-2xl font-bold text-red-600 dark:text-red-400">{{ data()!.leaveOverview.rejected }}</p>
                <p class="text-xs text-muted-foreground mt-1">Rechazados</p>
              </div>
            </div>
        </div>

        <!-- Recent Activity -->
        <div routerLink="/notifications" class="cursor-pointer group rounded-2xl border border-border/50 bg-card/80 backdrop-blur-sm p-6 hover:shadow-xl hover:shadow-primary/5 transition-all">
          <div class="flex items-center gap-3 mb-5">
            <div class="flex items-center justify-center w-10 h-10 rounded-xl bg-gradient-to-br from-purple-500/20 to-pink-500/20 text-purple-600 dark:text-purple-400 group-hover:scale-110 transition-transform">
              <lucide-icon name="bell" size="20"></lucide-icon>
            </div>
            <div>
              <h3 class="text-lg font-bold">Actividad Reciente</h3>
              <p class="text-xs text-muted-foreground">Últimas actualizaciones</p>
            </div>
          </div>
          <div class="space-y-3 max-h-[230px] overflow-y-auto pr-1">
            @for (activity of data()!.recentActivity; track activity.timestamp) {
              <div class="flex items-start gap-3 py-2 border-b border-border/20 last:border-0">
                <div class="mt-0.5 w-2 h-2 rounded-full flex-shrink-0"
                  [class.bg-blue-500]="activity.severity === 'info'"
                  [class.bg-yellow-500]="activity.severity === 'warning'"
                  [class.bg-red-500]="activity.severity === 'error'"
                  [class.bg-green-500]="activity.severity === 'success'"
                ></div>
                <div class="flex-1 min-w-0">
                  <p class="text-sm font-medium truncate">{{ activity.title }}</p>
                  <p class="text-xs text-muted-foreground truncate">{{ activity.description }}</p>
                </div>
                <span class="text-xs text-muted-foreground whitespace-nowrap">{{ getTimeAgo(activity.timestamp) }}</span>
              </div>
            } @empty {
              <div class="text-center text-muted-foreground text-sm py-4">
                Sin actividad reciente
              </div>
            }
          </div>
        </div>
      </div>

        @if (data()!.upcomingBirthdays.length > 0) {
          <!-- ═══ UPCOMING BIRTHDAYS ═══ -->
          <div class="rounded-2xl border border-border/50 bg-card/80 backdrop-blur-sm p-6">
            <div class="flex items-center gap-3 mb-5">
              <div class="flex items-center justify-center w-10 h-10 rounded-xl bg-gradient-to-br from-pink-500/20 to-rose-500/20 text-pink-600 dark:text-pink-400">
                <lucide-icon name="cake" size="20"></lucide-icon>
              </div>
              <div>
                <h3 class="text-lg font-bold">Próximos Cumpleaños 🎂</h3>
                <p class="text-xs text-muted-foreground">En los próximos 30 días</p>
              </div>
            </div>
            <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
              @for (bday of data()!.upcomingBirthdays; track bday.name) {
                <div class="flex items-center gap-3 p-3 rounded-xl bg-gradient-to-br from-pink-50/50 to-rose-50/50 dark:from-pink-900/10 dark:to-rose-900/10 border border-pink-200/30 dark:border-pink-800/20">
                  <div class="w-8 h-8 rounded-full bg-pink-100 dark:bg-pink-900/30 flex items-center justify-center text-pink-600 dark:text-pink-400 text-sm">
                    <lucide-icon name="user" size="14"></lucide-icon>
                  </div>
                  <div class="min-w-0">
                    <p class="text-sm font-semibold truncate">{{ bday.name }}</p>
                    <p class="text-xs text-muted-foreground">{{ bday.date }} • {{ bday.departmentName }}</p>
                  </div>
                </div>
              }
            </div>
          </div>
        }
      }
    </div>
  `,
  styles: [`
    :host {
      display: block;
    }

    @keyframes fadeIn {
      from { opacity: 0; transform: translateY(12px); }
      to { opacity: 1; transform: translateY(0); }
    }

    .animate-fadeIn {
      animation: fadeIn 0.5s ease-out forwards;
    }
  `]
})
export class DashboardComponent implements OnInit {
  private route = inject(ActivatedRoute);
  private dashboardService = inject(DashboardService);
 
  data = signal<DashboardData | null>(null);
  loading = signal(true);
  selectedPeriod = signal('week');

  // Gradient backgrounds for KPI cards
  kpiBg = [
    'bg-card/80 backdrop-blur-sm',
    'bg-card/80 backdrop-blur-sm',
    'bg-card/80 backdrop-blur-sm',
    'bg-card/80 backdrop-blur-sm',
    'bg-card/80 backdrop-blur-sm',
    'bg-card/80 backdrop-blur-sm',
    'bg-card/80 backdrop-blur-sm',
    'bg-card/80 backdrop-blur-sm',
  ];

  kpiBlobColor = [
    'bg-emerald-500',
    'bg-blue-500',
    'bg-violet-500',
    'bg-amber-500',
    'bg-rose-500',
    'bg-cyan-500',
    'bg-orange-500',
    'bg-teal-500',
  ];

  kpiCards = computed(() => {
    const d = this.data();
    if (!d?.kpis) return [];
    return [
      d.kpis.totalEmployees,
      d.kpis.activeEmployees,
      d.kpis.departmentsCount,
      d.kpis.pendingLeaves,
      d.kpis.turnoverRate,
      d.kpis.avgPerformance,
      d.kpis.absenteeismRate,
      d.kpis.payrollCost,
    ];
  });

  private barColors = [
    'linear-gradient(90deg, #10b981, #34d399)',
    'linear-gradient(90deg, #3b82f6, #60a5fa)',
    'linear-gradient(90deg, #8b5cf6, #a78bfa)',
    'linear-gradient(90deg, #f59e0b, #fbbf24)',
    'linear-gradient(90deg, #ef4444, #f87171)',
    'linear-gradient(90deg, #06b6d4, #22d3ee)',
    'linear-gradient(90deg, #ec4899, #f472b6)',
    'linear-gradient(90deg, #14b8a6, #2dd4bf)',
  ];

  ngOnInit() {
    // Use pre-fetched data from resolver
    const resolvedData = (this.route.snapshot.data as any)['stats'];
    if (resolvedData) {
      this.data.set(resolvedData.data);
      this.loading.set(false);
    } else {
      this.fetchDashboard();
    }
  }

  fetchDashboard() {
    this.loading.set(true);

    this.dashboardService.getDashboard(this.selectedPeriod()).subscribe({
      next: (res) => {
        this.data.set(res.data);
        this.loading.set(false);
      },
      error: () => {
        this.loading.set(false);
      }
    });
  }


  getBarWidth(count: number): number {
    const d = this.data();
    if (!d?.headcountByDepartment.length) return 0;
    const max = Math.max(...d.headcountByDepartment.map(d => d.count));
    return max > 0 ? (count / max) * 100 : 0;
  }

  getBarGradient(index: number): string {
    return this.barColors[index % this.barColors.length];
  }

  getTimeAgo(timestamp: string): string {
    const now = new Date();
    const date = new Date(timestamp);
    const diffMs = now.getTime() - date.getTime();
    const diffMin = Math.floor(diffMs / 60000);
    if (diffMin < 1) return 'ahora';
    if (diffMin < 60) return `hace ${diffMin}m`;
    const diffH = Math.floor(diffMin / 60);
    if (diffH < 24) return `hace ${diffH}h`;
    const diffD = Math.floor(diffH / 24);
    if (diffD < 7) return `hace ${diffD}d`;
    return date.toLocaleDateString('es', { month: 'short', day: 'numeric' });
  }
}
